driver:
  name: docker

platforms:
  - name: centos-7
    driver_config:
      image: corux/centos7-salt

provisioner:
  name: salt_solo
  formula: yarm
  pillars-from-files:
    yarn.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - yarn
  state_top:
    base:
      "*":
        - yarn

suites:
  - name: default
